vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       products:
           uri_prefix: /pokemon/species
           upload_destination: '%kernel.project_dir%/public/pokemon/image'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer