vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        species:
            uri_prefix: /pokemon/species
            upload_destination: '%kernel.project_dir%/public/pokemon/species'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer